### PR TITLE
Use the new section modifiers, not the ones in the formatting stack

### PR DESCRIPTION
**Pull request by bulinutza**

### CODE REVIEW

**Comment by dj2** [comment]
Thanks for the patch.

**Comment by bulinutza** [comment]
Hi Dan,

Could you also please bump the version of the gem?

**Comment by dj2** [comment]
I'll take a look tonight. It's been a while since I pushed a gem, heh.

**Comment by bulinutza** [comment]
It should be enough to increase the version like here:
https://github.com/dj2/Ruby-RTF/commit/f2c6c4a5d727e8b4337382520f45784c5e737b11

**Comment by dj2** [comment]
Done.

**Comment by bulinutza** [comment]
Thank you!

**Pull request merged**
